#ifndef RECIEVED_CONFIG_CONTROLLER_H
#define RECIEVED_CONFIG_CONTROLLER_H


void RecievedConfigController();


#define REACTION_ERORR_VCC_DONT_REACT 0
#define REACTION_ERORR_VCC_SEND_SMS 1
#define REACTION_ERORR_VCC_WRITE_ON_SD 2
#define REACTION_ERORR_VCC_SEND_GET 3
#define REACTION_ERORR_VCC_SEND_SMS_AND_GET 13


#endif